import os, sys
root_dir = os.path.dirname(File('SConscript').rfile().abspath + '/../../../../')
sys.path.insert(0, os.path.join(root_dir, 'tools/scons_helper'))
from platform_utils import Config
from test import TestBuilder
Import('CURRENT')
Import('ENV')
Import('CONFIG')
Import('LIB_PREFIX')
ROOT = os.getcwd().replace('\\', '/')
TEST_CONFIG = CONFIG.Copy()
TEST_CONFIG.Extend({
        "linux" : {
            "TARGET" : "ct",
            "LD_FLAGS" : "`icu-config --ldflags`",
            "LIBS" : ['pthread'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../../platform/thread/thread-posix.cc',
                         '../../platform/utils/utils-posix.cc',
                         '../../platform/fs/directory/directory-posix.cc']
            },
        'macos' : {
            "TARGET" : "ct",
            "LD_FLAGS" : "",
            "LIBS" : ['pthread'],
            "STATIC_LIBS" : [LIB_PREFIX + '/lib-osx/libicui18n.a', LIB_PREFIX + '/lib-osx/libicuio.a', LIB_PREFIX + '/lib-osx/libiculx.a', LIB_PREFIX + '/lib-osx/libicudata.a', LIB_PREFIX + '/lib-osx/libicuuc.a', LIB_PREFIX + '/lib-osx/libicule.a'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../../platform/thread/thread-posix.cc',
                         '../../platform/utils/utils-posix.cc',
                         '../../platform/fs/directory/directory-posix.cc']
            },
        "win32" : {
            "LD_FLAGS" : "/NOLOGO /MACHINE:X86",
            "LIBS" : ['advapi32.lib'],
            "STATIC_LIBS" : [LIB_PREFIX + '/lib-win32/debug/icuin.lib', LIB_PREFIX + '/lib-win32/debug/icudt.lib', LIB_PREFIX + '/lib-win32/debug/icuuc.lib'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../../platform/thread/thread-win32.cc',
                         '../../platform/utils/utils-win32.cc',
                         '../../platform/fs/directory/directory-win32.cc']
            }
        })
TEST_CONFIG.set_base(ROOT)
builder = TestBuilder(ARGUMENTS.get('mode'), ['ut.cc',
                                              'translator.cc',
                                              '../../nexc/nexc.cc',
                                              '../../nexc/parser/parser.cc',
                                              '../../nexc/tokens/symbol_list.cc',
                                              '../builder/ast_builder.cc',
                                              '../../nexc/binding/parser_connector.cc',
                                              '../ast.cc',
                                              '../../nexc/tokens/js_token.cc',
                                              '../../nexc/tokens/token_info.cc',
                                              '../../nexc/loader/loader.cc',
                                              '../../nexc/scanner/encoding/encoding.cc',
                                              '../../nexc/scanner/scanner.cc',
                                              '../../nexc/scanner/source_stream.cc',
                                              '../../nexc/scanner/token_stream.cc',
                                              '../../nexc/compilation_info/compilation_info.cc',
                                              '../../nexc/events/compilation_event/compilation_event.cc',
                                              '../../memory/pool.cc',
                                              '../../platform/fs/stat/stat.cc',
                                              '../../utils/error_reporter.cc',
                                              '../../platform/fs/mkdir/mkdir.cc',
                                              '../../platform/fs/rm/rm.cc',
                                              '../../platform/fs/mv/mv.cc',
                                              '../../platform/fs/path/path.cc',
                                              '../../consts/consts.cc',
                                              '../../platform/fs/virtual_directory/virtual_directory.cc',
                                              'processors/array_processor.cc',
                                              'processors/dsta_processor.cc',
                                              'processors/function_processor.cc',
                                              'processors/object_processor.cc',
                                              'processors/trait_processor.cc',
                                              'processors/export_processor.cc',
                                              'processors/import_processor.cc',
                                              'processors/variable_processor.cc',
                                              'processors/call_processor.cc',
                                              'processors/iteration_processor.cc',
                                              'processors/class_processor.cc',
                                              'processors/fileroot_processor.cc',
                                              'processors/module_processor.cc',
                                              'processors/syntax_sugar_processor.cc',
                                              'processors/yield_processor.cc',
                                              '../../nexc/events/io_event/io_event.cc'], ENV, TEST_CONFIG)
builder.Build(CURRENT + '/src', ROOT, CURRENT)

