import os, sys
root_dir = os.path.dirname(File('SConscript').rfile().abspath + '/../../../../')
sys.path.insert(0, os.path.join(root_dir, 'tools/scons_helper'))
from platform_utils import Config
from test import TestBuilder
Import('CURRENT')
Import('ENV')
Import('CONFIG')
Import('LIB_PREFIX')
ROOT = os.getcwd().replace('\\', '/')
TEST_CONFIG = CONFIG.Copy()
TEST_CONFIG.Extend({
        "linux" : {
            "TARGET" : "ct",
            "LD_FLAGS" : "",
            "LIBS" : ['pthread'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../../platform/thread/thread-posix.cc',
                         '../../platform/utils/utils-posix.cc',
                         '../../platform/fs/directory/directory-posix.cc']
            },
        'macos' : {
            "TARGET" : "ct",
            "LD_FLAGS" : "",
            "LIBS" : ['pthread'],
            "STATIC_LIBS" : [LIB_PREFIX + '/lib-osx/libicui18n.a', LIB_PREFIX + '/lib-osx/libicuio.a', LIB_PREFIX + '/lib-osx/libiculx.a', LIB_PREFIX + '/lib-osx/libicudata.a', LIB_PREFIX + '/lib-osx/libicuuc.a', LIB_PREFIX + '/lib-osx/libicule.a'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../../platform/thread/thread-posix.cc',
                         '../../platform/utils/utils-posix.cc',
                         '../../platform/fs/directory/directory-posix.cc']
            },
        "win32" : {
            "TARGET" : "ct.exe",
            "LD_FLAGS" : "/NOLOGO /MACHINE:X86 /LTCG",
            "LIBS" : [LIB_PREFIX + '/lib-win32/icuin.lib', LIB_PREFIX + '/lib-win32/icudt.lib', LIB_PREFIX + '/lib-win32/icuuc.lib'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../../platform/thread/thread-win32.cc',
                         '../../platform/utils/utils-win32.cc',
                         '../../platform/fs/directory/directory-win32.cc']
            }
        })
TEST_CONFIG.set_base(ROOT)
builder = TestBuilder(ARGUMENTS.get('mode'), ['ct.cc',
                                              '../nexc.cc',
                                              '../parser/parser.cc',
                                              '../tokens/symbol_list.cc',
                                              '../../ast/builder/ast_builder.cc',
                                              '../binding/parser_connector.cc',
                                              '../../ast/ast.cc',
                                              '../tokens/js_token.cc',
                                              '../tokens/token_info.cc',
                                              '../loader/loader.cc',
                                              '../scanner/encoding/encoding.cc',
                                              '../scanner/scanner.cc',
                                              '../scanner/source_stream.cc',
                                              '../scanner/token_stream.cc',
                                              '../compilation_info/compilation_info.cc',
                                              '../events/compilation_event/compilation_event.cc',
                                              '../../memory/pool.cc',
                                              '../../platform/fs/stat/stat.cc',
                                              '../../utils/error_reporter.cc',
                                              '../../platform/fs/mkdir/mkdir.cc',
                                              '../../platform/fs/rm/rm.cc',
                                              '../../platform/fs/mv/mv.cc',
                                              '../../platform/fs/path/path.cc',
                                              '../../consts/consts.cc',
                                              '../../platform/fs/virtual_directory/virtual_directory.cc',
                                              '../events/io_event/io_event.cc'], ENV, TEST_CONFIG)
builder.Build(CURRENT + '/src', ROOT, CURRENT)

