import os, sys
root_dir = os.path.dirname(File('SConscript').rfile().abspath + '/../../../../')
sys.path.insert(0, os.path.join(root_dir, 'tools/scons_helper'))
from platform_utils import Config
from test import TestBuilder
Import('CURRENT')
Import('ENV')
Import('CONFIG')
Import('LIB_PREFIX')
ROOT = os.getcwd().replace('\\', '/')
TEST_CONFIG = CONFIG.Copy()
TEST_CONFIG.Extend({
        "linux" : {
            'RELEASE' : '`icu-config --ldflags`',
            "DEBUG" : '`icu-config --ldflags`',
            "LD_FLAGS" : "",
            "LIBS" : ['pthread'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../platform/thread/thread-posix.cc',
                         '../platform/utils/utils-posix.cc']
            },
        'macos' : {
            "LD_FLAGS" : "",
            "LIBS" : ['pthread'],
            "STATIC_LIBS" : [],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../platform/thread/thread-posix.cc',
                         '../platform/utils/utils-posix.cc']
            },
        "win32" : {
            "LD_FLAGS" : "/NOLOGO /MACHINE:X86 /LTCG",
            "LIBS" : [],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : ['../platform/thread/thread-win32.cc',
                         '../platform/utils/utils-win32.cc']
            }
        })

TEST_CONFIG.set_base(ROOT)
builder = TestBuilder('release', ['ut.cc','pool.cc', '../platform/fs/stat/stat.cc', '../platform/fs/mv/mv.cc', '../../misc/profiler.cc'], ENV, TEST_CONFIG)
builder.Build(CURRENT + '/src', ROOT, CURRENT, True)

