import os, sys
root_dir = os.path.dirname(File('SConscript').rfile().abspath + '/../../../../')
sys.path.insert(0, os.path.join(root_dir, 'tools/scons_helper'))
from platform_utils import Config
from test import TestBuilder
Import('CURRENT')
Import('ENV')
Import('CONFIG')
ROOT = os.getcwd().replace('\\', '/')
TEST_CONFIG = CONFIG.Copy()
TEST_CONFIG.Extend({
        "linux" : {
            "LD_FLAGS" : "",
            "LIBS" : ['pthread'],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : []
            },
        'macos' : {
            "LD_FLAGS" : "",
            "LIBS" : [],
            "STATIC_LIBS" : [],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : []
            },
        "win32" : {
            "LD_FLAGS" : "/NOLOGO /MACHINE:X86",
            "LIBS" : [],
            "EXCLUDE_FILES" : [],
            "DEPENDS" : []
            }
        })
TEST_CONFIG.set_base(ROOT)
builder = TestBuilder(ARGUMENTS.get('mode'), ['ut.cc', 'stat.cc'], ENV, TEST_CONFIG)
builder.Build(CURRENT + '/src', ROOT)

